### ISSUE TITLE
current buffer being typed is being highlighted Pydroid 3 terminal

### ISSUE THREAD

**Issue by realKarthikNair** [kdrag0n/inter-font-pack#1]
Let me be straight - i won't be able to explain this issue as text - the developer is requested to install Pydroid 3 app and try to type in something in its intrepretor mode or terminal mode.

**Comment by kdrag0n** [comment]
I don't understand what you mean. Can you send a screenshot and/or screen recording?

**Comment by realKarthikNair** [comment]
Issue solved ! Sorry for the inconvenience !
