### ISSUE TITLE
Unsupported Emojis. 

### ISSUE THREAD

**Issue by Nakamerica** [kdrag0n/inter-font-pack#3]
Hi, the font pack is great, I've been using it for quite some time, however I've noticed a couple of emojis that are not supported by the pack. Two screenshots are attached: one without the font pack, and one with, so as to point out the unsupported emojis. 

![msg-1334417859-40526](https://user-images.githubusercontent.com/88226614/158753751-984345e0-128b-4544-a4ea-d4c62cbb7201.jpg)

![msg-1334417859-40527](https://user-images.githubusercontent.com/88226614/158753765-7b55b4b7-4852-48a2-96f1-c4cfb800f6ec.jpg)

Please let me know if any more information is wanted, thanks.

**Comment by VladWinner** [comment]
This module doesn't replace emoji .TTFs.
Have you tried installing emoji module like [this one](https://t.me/rkbdiemoji/233)?

**Comment by Nakamerica** [comment]
> This module doesn't replace emoji .TTFs.

Are you sure? Iirc it does...

The t.me link you sent is to a private chat... so I cannot access that file.

**Comment by VladWinner** [comment]
> I cannot access that file.

I replaced t.me link, check again

**Comment by Nakamerica** [comment]
Ah thank you, i was aware of rkbdi's work but not his emoji modules, will try it out.
